### ISSUE TITLE
Create project template error - System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by cirrusone** [AvaloniaUI/TemplateStudio#20] opened 2023-08-10 11:22 UTC
### Describe the bug

The template studio has error on latest version of VS preview

![Untitled](https://github.com/AvaloniaUI/TemplateStudio/assets/10389314/e10a8e43-04d2-4b71-97c7-dda4830e2873)

### To Reproduce

 1. New Project
 2. Avalonia C# Project (template studio)
 3. Click Create

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<Microsoft.TemplateEngine.Abstractions.ITemplate> Microsoft.TemplateEngine.Edge.Settings.ScanResult.get_Templates()'.
   at Microsoft.Templates.Core.TemplatesRepository.GetAll()
   at Microsoft.Templates.Core.TemplatesRepository.GetSupportedProjectTypes(UserSelectionContext context)
   at Microsoft.Templates.Core.TemplatesRepository.GetProjectTypes(UserSelectionContext context)
   at Microsoft.Templates.UI.Services.DataService.LoadProjectTypes(ObservableCollection`1 projectTypes, UserSelectionContext context)
   at Microsoft.Templates.UI.ViewModels.NewProject.ProjectTypeViewModel.<LoadDataAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.ViewModels.NewProject.MainViewModel.<OnTemplatesAvailableAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.Views.NewProject.NewProjectWizardShell.<OnLoaded>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Microsoft.Internal.VisualStudio.PlatformUI.WindowHelper.ShowModal(Window window, IntPtr parent)
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellUI.<ShowModalAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellUI.<>c__DisplayClass7_0.<<ShowModal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellUI.ShowModal(IWindow shell)
   at Microsoft.Templates.UI.Launcher.WizardLauncher.LaunchWizardShell(IWizardShell wizardShell)
   at Microsoft.Templates.UI.Launcher.WizardLauncher.StartWizard(IWizardShell wizardShell, WizardTypeEnum wizardType)
```

### About your setup

 - Visual Studio Version:   Visual Studio 2022 Version 17.8.0 Preview 1.0
 - Template Studio Wizard Version:  latest
 - Windows Build: dotnet-sdk-8.0.100-preview.7.23376.3-win-x64.exe

**Comment by sharpninja** [comment] 2023-09-14 18:46
I can confirm this bug.

**Comment by drewnoakes** [comment] 2023-11-08 03:17
Also reported in https://developercommunity.visualstudio.com/t/Visual-Studio-Preview-178-P1-Template-E/10454227.

**Comment by maxkatz6** [comment] 2024-07-22 21:08
Apparently it was fixed in Visual Studio.
I can't reproduce it.
https://developercommunity.visualstudio.com/t/Visual-Studio-Preview-178-P1-Template-E/10454227

**Closed by maxkatz6** 2024-07-22 21:08 UTC
Labels: bug
